version: '3.3'

services:
  customer-service:
    restart: unless-stopped
    image: kyrylrs/customer-service
    ports:
      - "9101:9101"
    depends_on:
      - customer_db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/customer.yaml:/config.yaml
    command: run service

  staff-service:
    restart: unless-stopped
    image: kyrylrs/staff-service
    ports:
      - "9102:9102"
    depends_on:
      - staff_db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/staff.yaml:/config.yaml
    command: run service


  staff_db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - database_data:/var/lib/postgresql/data

  customer_db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local