version: '3.3'

services:
  auth-service:
    restart: unless-stopped
    image: kyrylrs/auth-service
    ports:
      - "9110:9110"
    depends_on:
      - auth-db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/auth.yaml:/config.yaml
    entrypoint: sh -c "auth-service migrate up && auth-service run service"

  auth-db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - auth-db:/var/lib/postgresql/data

  staff-service:
    restart: unless-stopped
    image: kyrylrs/staff-service
    ports:
      - "9102:9102"
    depends_on:
      - staff-db
      - auth-service
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/staff.yaml:/config.yaml
    entrypoint: sh -c "staff-service migrate up && staff-service run service"


  staff-db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - staff-db:/var/lib/postgresql/data


  web_client:
    image: csca-front-local
    restart: unless-stopped
    ports:
      - "8060:80"

  customer-service:
    restart: unless-stopped
    image: kyrylrs/customer-service
    ports:
      - "9101:9101"
    depends_on:
      - customer-db
      - auth-service
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/customer.yaml:/config.yaml
    entrypoint: sh -c "customer-service migrate up && customer-service run service"

  customer-db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - customer-db:/var/lib/postgresql/data

  menu-service:
    restart: unless-stopped
    image: captainshepard/menu-service
    ports:
      - "9105:9105"
    depends_on:
      - menu-db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/menu.yaml:/config.yaml
    entrypoint: sh -c "menu-service migrate up && menu-service run service"


  menu-db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - menu-db:/var/lib/postgresql/data

  cafe-service:
    restart: unless-stopped
    image: captainshepard/cafe-service
    ports:
      - "9106:9106"
    depends_on:
      - cafe-db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/cafe.yaml:/config.yaml
    entrypoint: sh -c "cafe-service migrate up && cafe-service run service"


  cafe-db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - cafe-db:/var/lib/postgresql/data

  order-service:
    restart: unless-stopped
    image: hodorbrain/order-service
    ports:
      - "9107:9107"
    depends_on:
      - order-db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/order.yaml:/config.yaml
    entrypoint: sh -c "order-service migrate up && order-service run service"


  order-db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - order-db:/var/lib/postgresql/data


volumes:
  staff-db:
    driver: local
  auth-db:
    driver: local
  customer-db:
    driver: local
  menu-db:
    driver: local
  cafe-db:
    driver: local
  order-db:
    driver: local
