version: '3.3'

services:
  auth-service:
    restart: unless-stopped
    image: kyrylrs/auth-service
    ports:
      - "9110:9110"
    depends_on:
      - auth_db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/auth.yaml:/config.yaml
    entrypoint: sh -c "auth-service migrate up && auth-service run service"

  auth_db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - auth_db:/var/lib/postgresql/data


  customer-service:
    restart: unless-stopped
    image: kyrylrs/customer-service
    ports:
      - "9101:9101"
    depends_on:
      - customer_db
      - auth-service
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/customer.yaml:/config.yaml
    entrypoint: sh -c "customer-service migrate up && customer-service run service"

  customer_db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - customer_db:/var/lib/postgresql/data

  staff-service:
    restart: unless-stopped
    image: kyrylrs/staff-service
    ports:
      - "9102:9102"
    depends_on:
      - staff_db
      - auth-service
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/staff.yaml:/config.yaml
    entrypoint: sh -c "staff-service migrate up && staff-service run service"


  staff_db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - staff_db:/var/lib/postgresql/data

  menu-service:
    restart: unless-stopped
    image: captainshepard/menu-service
    ports:
      # localhost:docker
      - "9105:9105"
    depends_on:
      - menu-db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/menu.yaml:/config.yaml
    entrypoint: sh -c "menu-service migrate up && menu-service run service"


  menu-db:
    image: postgres
    restart: always
    ports:
      # localhost:docker
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - menu-db:/var/lib/postgresql/data


volumes:
  staff_db:
    driver: local
  auth_db:
    driver: local
  customer_db:
    driver: local
  menu-db:
    driver: local
