log:
  disable_sentry: true
  level: "info"

db:
  url: "postgres://postgres:postgres@auth_db/postgres?sslmode=disable"

listener:
  addr: :9110

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: auth-service
  service_port: 80
