log:
  disable_sentry: true
  level: "info"

db:
  url: "postgres://postgres:postgres@menu-db/postgres?sslmode=disable"

# if docker false, the first entry point will be used, otherwise the second!!!
endpoints:
  docker: true
  services:
    - service: "auth-service"
      entry_points:
        - "localhost:9110/jwt/login"
        - "auth-service:9110/jwt/login"
    - service: "staff-service"
      entry_points:
        - "localhost:9102/jwt/user"
        - "staff-service:9102/jwt/user"
    - service: "cafe-service"
      entry_points:
        - "localhost:9106/integrations/cafe-service/cafes/"
        - "cafe-service:9106/integrations/cafe-service/cafes/"
    - service: "warehouse-service"
      entry_points:
        - "localhost:9109/integrations/warehouse-service/ingredients/"
        - "warehouse-service:9109/integrations/warehouse-service/ingredients/"

listener:
  addr: :9105

cop:
  disabled: true
